import type { EvidenceSynthesisRule, PersonaId } from '../../v3-types'

const rule = (
  id: string,
  persona: PersonaId,
  requiredAnswers: string[],
  category: EvidenceSynthesisRule['category'],
  priority: number,
  text: string,
  optionalAnswers: string[] = [],
  excludedAnswers: string[] = [],
): EvidenceSynthesisRule => ({
  id, personaTags: [persona], requiredAnswers, optionalAnswers, excludedAnswers, category, priority, text,
})

export const evidenceSynthesisRules: EvidenceSynthesisRule[] = [
  rule('spf-runtime-dependency', 'single_point_failure', ['Q4A', 'Q22A'], 'expression_org', 98,
    '你不在的时候，项目容易先暂停思考；你在的时候，大家又默认这块得等你点一下头。', ['Q5A', 'Q18A'], ['Q18C']),
  rule('spf-judgment-dependency', 'single_point_failure', ['Q5A', 'Q17A'], 'work_behavior', 94,
    '别人不只是习惯把活给你，关键时候还习惯等你先判断这件事到底该怎么走。', ['Q22A', 'Q9A']),
  rule('spf-history-dependency', 'single_point_failure', ['Q5D', 'Q18D'], 'human_moment', 92,
    '组织的历史包袱没有消失，只是被压缩成一句：“这事问你，你应该还记得。”', ['Q4D']),
  rule('spf-incident-magnet', 'single_point_failure', ['Q9D', 'Q22A'], 'expression_org', 88,
    '新问题刚掉进群里，系统还没分配负责人，通讯录已经提前把你算进去了。', ['Q2A', 'Q5A']),

  rule('invisible-front-back', 'invisible_contributor', ['Q2A', 'Q13D'], 'expression_org', 99,
    '事情出问题的时候你通常站得挺前，事情做完以后又会自然往后退两步。', ['Q21C', 'Q21D']),
  rule('invisible-real-work-no-subject', 'invisible_contributor', ['Q1A', 'Q16D'], 'expression_org', 95,
    '你手里确实有能撑场面的项目，只是写到总结里，主语经常自动变成了“团队”。', ['Q21C']),
  rule('invisible-emergency-credit', 'invisible_contributor', ['Q7A', 'Q21D'], 'work_behavior', 92,
    '急活来了你会先把关键部分顶住；等成果落地，名字却可能比问题更晚被看见。', ['Q2A']),
  rule('invisible-fix-then-fade', 'invisible_contributor', ['Q9A', 'Q13D'], 'human_moment', 88,
    '你擅长先把没人认领的问题拆开，至于后来谁记得这一步是谁做的，系统没有证据。', ['Q16C', 'Q21C']),

  rule('captioner-result-first', 'result_captioner', ['Q1A', 'Q13A'], 'expression_org', 98,
    '你不只知道哪件事是自己扛的，也知道汇报时先把结果和归属放到组织看得见的位置。', ['Q12A']),
  rule('captioner-closed-loop', 'result_captioner', ['Q12A', 'Q21A'], 'expression_org', 96,
    '从临时追问到年底算功劳，你倾向于让进度、结果和名字形成一个不用考古的闭环。', ['Q13A']),
  rule('captioner-memory-builder', 'result_captioner', ['Q16A', 'Q13A'], 'work_behavior', 92,
    '你很清楚组织的短期记忆只有两周，所以每次交差，都会把数据、结论和“谁干的”一起加粗。', ['Q21A']),
  rule('captioner-work-translator', 'result_captioner', ['Q2A', 'Q12A'], 'work_behavior', 88,
    '你能先把火救下来，也能很快把现场翻译成进度、风险和下一步，而不是只留下“已处理”。', ['Q1A']),

  rule('middleware-route-owner', 'wild_middleware', ['Q9B', 'Q10B'], 'work_behavior', 98,
    '问题进来以后，你脑子里首先出现的不是流程图，而是这件事真正应该找谁。', ['Q5C']),
  rule('middleware-human-index', 'wild_middleware', ['Q5C', 'Q10B'], 'expression_org', 94,
    '别人来问你不一定因为你负责，而是因为你知道哪条线能直接接到真正拍板的人。', ['Q9B']),
  rule('middleware-resource-router', 'wild_middleware', ['Q2B', 'Q15B'], 'work_behavior', 91,
    '遇到复杂局面，你会先把能打的人拉齐，再去借一份活人经验让事情真正动起来。', ['Q9B']),
  rule('middleware-unofficial-path', 'wild_middleware', ['Q10D', 'Q5C'], 'human_moment', 87,
    '正式流程卡住时，你会启动通讯录里的民间接口；组织架构图没画，但现实一直在走。', ['Q9B']),

  rule('patcher-before-official', 'reality_patcher', ['Q15C', 'Q17C'], 'work_behavior', 99,
    '正式方案还没出生，你的临时版本已经开始上班，而且会先小范围跑一圈看看坑在哪。', ['Q9A']),
  rule('patcher-route-and-prototype', 'reality_patcher', ['Q10D', 'Q15C'], 'work_behavior', 95,
    '流程不给路时你会自己找路，模板没出现时你会先糊一版能跑的，现实很少等手续齐全。', ['Q17C']),
  rule('patcher-problem-to-trial', 'reality_patcher', ['Q9A', 'Q17C'], 'expression_org', 91,
    '群里还在争论可不可行，你已经先糊了个能跑的版本出来：“先试一下，不行再说。”', ['Q15C']),
  rule('patcher-rescue-prototype', 'reality_patcher', ['Q2A', 'Q15C'], 'human_moment', 87,
    '你对“先救下来再说”很熟，很多后来被称为方案的东西，最初只是你先做的能跑版本。', ['Q10D']),

  rule('firewall-scope-first', 'desk_firewall', ['Q6A', 'Q7A'], 'work_behavior', 99,
    '你不是不接活，只是现在习惯先把范围问清楚，再决定今天到底先救哪一部分。', ['Q17D']),
  rule('firewall-owner-and-size', 'desk_firewall', ['Q8B', 'Q15A'], 'work_behavior', 95,
    '版本再乱、活再新，你都会先确认谁拍板、这锅多大，以及做到哪儿才算真正结束。', ['Q2C']),
  rule('firewall-responsibility-trace', 'desk_firewall', ['Q2C', 'Q17B'], 'expression_org', 91,
    '方向有坑时你不会直接消失：先确认责任，再找合适的场合把风险和替代路径说清楚。', ['Q17D']),
  rule('firewall-boundary-carry', 'desk_firewall', ['Q6A', 'Q17A'], 'human_moment', 88,
    '你会先问清“顺手”到底有多顺手，但真遇到风险，也愿意把问题和另一条路一起摆上桌。', ['Q7A']),

  rule('weather-signal-to-private-action', 'org_weather_station', ['Q3B', 'Q17B'], 'work_behavior', 97,
    '你会先确认空气里那个信号是什么意思，再选择一个更合适的场合把真正的风险说出来。', ['Q12B']),
  rule('weather-room-change', 'org_weather_station', ['Q11A', 'Q20C'], 'expression_org', 94,
    '你能看见房间里的表达方式什么时候变了，也会顺手调整自己的材料，而不是只围观天气。', ['Q12B']),
  rule('weather-prepare-before-talk', 'org_weather_station', ['Q25B', 'Q12B'], 'work_behavior', 91,
    '领导一句“聊两句”，你会先判断他为什么突然问起，再把过去半年的重点项目过一遍。', ['Q20C']),
  rule('weather-adjust-not-panic', 'org_weather_station', ['Q3A', 'Q17B'], 'human_moment', 88,
    '看到群里的气压骤降，你没有跟着发“收到”，而是先私聊两个关键的人探探水温。', ['Q12B'], ['Q20D']),

  rule('stable-transferable', 'stable_worker', ['Q4C', 'Q18C'], 'work_behavior', 86,
    '你既不会把自己包装成唯一入口，也没有完全退出现场；交接能跑，历史包袱偶尔还会回头。', ['Q8B']),
  rule('stable-recognized-reliable', 'stable_worker', ['Q1B', 'Q22B'], 'expression_org', 84,
    '你做过的难活有人知道，领导也倾向于把重要事情交给你，属于组织默认会继续使用的配置。', ['Q5B']),
  rule('stable-ordinary-human', 'stable_worker', ['Q6B', 'Q20A'], 'human_moment', 80,
    '系统没发现特别离谱的属性。主要发现你会正常排时间、正常恭喜同事，然后继续上班。', ['Q23A']),
]
